spring:
  datasource:
    username: kzm_vlad
    password: 123root@
    driverClassName: com.mysql.cj.jdbc.Driver
    driverDialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:postgresql://localhost/webchatdb
  jpa:
    hibernate:
      ddl-auto: validate

  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
      bindings:
        kafka:
          binder:
            headers: version, action, EventVersion, EntityVersion
        user-event-output:
          destination: user-event
          contentType: application/json
          producer:
            headerMode: raw

server:
  port: 8087

redis:
  host: 127.0.0.1